spring.application.name=ecom-proj

spring.datasource.url=jdbc:h2:mem:janlo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sameenaparves
spring.datasource.password=janlo


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

